---
# General Elastic Cloud Enterprise relevant settings
ece_version: 2.6.2
ece_docker_registry: docker.elastic.co
ece_docker_repository: cloud-enterprise
docker_config: ""
ece_installer_url: "https://download.elastic.co/cloud/elastic-cloud-enterprise.sh"
ece_runner_id: "{{ ansible_default_ipv4.address }}"

elastic_user: "elastic"
elastic_home: "/home/elastic"
filesystem_type: "xfs"
fs_options: "defaults,nofail,pquota,prjquota"
runner_name: "runner-{{ inventory_hostname_short }}"

docker_storage_driver: overlay2
docker_version: "19.03"
docker_version_map:
  "19.03":
    package:
      - docker-ce=5:19.03.13*
      - docker-ce-cli=5:19.03.13*
      - containerd.io
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    keys:
      server: https://download.docker.com/linux/ubuntu/gpg
      id: 0EBFCD88

# Overall setup variables (like package versions)
device_name: "/dev/sda3"
data_dir: /mnt/data
force_xfc: false

# Misc. variables (like sysctl settings file, etc.)
sysctl_settings_file: "/etc/sysctl.d/70-cloudenterprise.conf"
system_limits_file: "/etc/security/limits.d/70-cloudenterprise.conf"

# Memory settings
memory:
  runner: 1G
  allocator: 4G
  proxy: 8G
  zookeeper: 4G
  director: 1G
  constructor: 4G
  adminconsole: 4G

# Elastic Cloud Enterprise - Support Diagnostics Settings
ece_supportdiagnostics_url: "https://github.com/elastic/ece-support-diagnostics/archive/v1.1.tar.gz"
ece_supportdiagnostics_result_path: "/tmp/ece-support-diagnostics"
fetch_diagnostics: false

# General settings for docker environment
docker_bridge_ip: "172.17.42.1/16"
