---
  - name: create /etc/systemd/system/docker.service.d folder
    become: yes
    file:
        path: /etc/systemd/system/docker.service.d
        state: directory
        mode: 0755
        owner: root
        group: root

  - name: Copy docker.conf to etc/systemd/system/docker.service.d folder
    become: yes
    template:
        src: docker.conf
        dest: /etc/systemd/system/docker.service.d/docker.conf
        mode: 0644
        force: yes
        owner: root
    notify:
        - reload docker daemon
        - restart docker