---
  - name: install ECE
    become: yes
    become_user: elastic
    shell: "/tmp/elastic-cloud-enterprise.sh install --cloud-enterprise-version {{ ece_platform.version }} --docker-registry {{ ece_docker_registry }} \
            --runner-id {{ runner_name }}  --roles {{ role }} \
            --availability-zone {{ zone }} --memory-settings {{ memory_settings }}"
    register: result
    environment:
      PATH: '$PATH:/usr/sbin:/bin:/usr/bin' # Have to use it because ansible switches to elastic user using sudo su -, PATH is not set properly. 

  - name: Remember the bootstrap secrets
    command: cat {{ data_dir }}/elastic/bootstrap-state/bootstrap-secrets.json
    register: secrets
  
  - name: Fetch the bootstrap secrets
    fetch:
      src: "{{ data_dir }}/elastic/bootstrap-state/bootstrap-secrets.json"
      dest: bootstrap-secrets.local.json
      flat: yes
  
  - set_fact:
      install_secrets: "{{ secrets.stdout|from_json }}"
  
  - set_fact:
      adminconsole_root_password: "{{ install_secrets.adminconsole_root_password }}"
  
  - set_fact:
      primary_hostname: "{{ inventory_hostname }}"